name: "Calculate Semantic Version, update files, and Create Tag"
description: >
  Calculates a new semantic version string based on conventional commits.
  Updates standard project files with the current version, commits them, and
  adds a tag.

on:
  workflow_call:
    inputs:
      package_json:
        description: 'Update version in package.json.'
        required: false
        type: boolean
        default: false
      package_json_dir:
        description: 'Optional. The dir where package.json is located.'
        required: false
        type: string
        default: ''
      style_css:
        description: 'Update version in style.css.'
        required: false
        type: boolean
        default: false
      style_css_dir:
        description: 'Optional. The dir where style.css is located.'
        required: false
        type: string
        default: ''
      wp_plugin_file:
        description: 'Update version in the WordPress plugin file.'
        required: false
        type: boolean
        default: false
      wp_plugin_file_dir:
        description: 'Optional. The dir where WordPress plugin file is located.'
        required: false
        type: string
        default: ''

# Write access to the repo is needed to commit and add a tag.
permissions:
  contents: write

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ vars.BSU_BUILDER_APP_ID }}
          private-key: ${{ secrets.BSU_BUILDER_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Get workflow version
        id: workflow-version
        uses: canonical/get-workflow-version-action@v1
        with:
          # Repository where reusable workflow is located
          repository-name: canonical/data-platform-workflows
          # Name of reusable workflow
          file-name: version-increment.yml
          # Only required for private repositories
          github-token: ${{ steps.generate-token.outputs.token }}

      - name: Checkout central actions
        uses: actions/checkout@v6
        with:
          repository: BemidjiState/.github
          # Use the extracted output to target the exact tag/branch
          ref: ${{ steps.workflow-version.outputs.sha }}
          path: dot-github-org-repo

      - name: Calculate version
        id: calculate-version
        uses: bitshifted/git-auto-semver@v2
        with:
          # Running on main will calculate semver. Otherwise a git hash is used.
          main_branch: ${{ github.ref_name }}
          create_tag: false  # A tag will be created at the last step.
          tag_prefix: ""

      - name: Update the version in project files
        uses: ./dot-github-org-repo/.github/actions/version-update-files
        with:
          version: ${{ steps.calculate-version.outputs.version-string }}
          package_json: ${{ inputs.package_json }}
          package_json_dir: ${{ inputs.package_json_dir }}
          style_css: ${{ inputs.style_css }}
          style_css_dir: ${{ inputs.style_css_dir }}
          wp_plugin_file: ${{ inputs.wp_plugin_file }}
          wp_plugin_file_dir: ${{ inputs.wp_plugin_file_dir }}

      - name: Cleanup reusable workflow/action repository
        run: |
          rm -rf dot-github-org-repo

      - name: Commit version file changes and create tag
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: 'chore: bump version to ${{ steps.calculate-version.outputs.version-string }}'
          commit_options: '--no-verify'  # Bypass pre-commit hooks.
          tag_name: '${{ steps.calculate-version.outputs.version-string }}'
          skip_dirty_check: true  # Commit even if no files changed.
